#
# Configuration for staging environment
#
version: 1.0
app:
  # build id to deploy. if 'version' is commented out, the application is not deployed
  version: ""

  # DB2 service
  # Note: "services" variable here is used to initiate private connection gateway between EASe Java and DB2
  # when both servcies are at private endpoints. But currently for pen test, we're using DB2 public endpoint (see db2HostName value below), 
  # therefore, this "services" variable has no effect.
  #services:
  #  - type: db2
  #    name: Db2-nd-mei-easej
    
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 4 gb
    cpu: 1

  # List of environment variables that are set for the application
  env:
    - name: JVM_ARGS 
      value: "-Xms=1024m"
    #- name: WLP_LOGGING_CONSOLE_FORMAT
    #  value: DEV    

  # List of variables that can be referenced in the server.xml
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    #uncomment when using Dev instnace - name: OIDC_DISCOVERY_HOST
    # value: "https://mei-easej-db2-academic-way-8529.staging.us-east.c2.appflow.dev.ibmappdomain.cloud/"
    - name: OIDC_DISCOVERY_HOST
      value: https://mei-stg-db2test-ha0k7v8wf4.staging.us-east.c2.appflow.test.ibmappdomain.cloud/  
    - name: db2HostName
      value: "2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud"
    - name: db2Port
      value: "30756"
    - name: dbName
      value: "bludb"
    - name: db2UserName
      value: "zpb97924"
      
